version: '3'
services:
  db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=cyber_proj
      - MYSQL_USER=cyber_user
      - MYSQL_PASSWORD=123456
      - MYSQL_ROOT_HOST=%
    volumes:
      - /tmp/app/mysqld:/var/run/mysqld
      - ./db:/var/lib/mysql
    networks:
      - db
    healthcheck:
      test: "mysqladmin ping -h localhost"
      interval: 1s
      timeout: 1s
      retries: 60
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DJANGO_DATABASE=docker
    depends_on:
      - db
    networks:
      - external-net
      - db

networks:
  external-net:
    external:
      name: external-net
  db:
    driver: bridge
