version: '3'
services:
  db:
    container_name: db
    image: mysql
    env_file:
      - .env.mysql
    volumes:
      - ./mysqld:/var/run/mysqld
      - ./db:/var/lib/mysql
    networks:
      - db
    healthcheck:
      test: "mysqladmin ping -h localhost"
      interval: 1s
      timeout: 1s
      retries: 60
  smtp:
    container_name: smtp
    image: msztolcman/sendria:v2.2.2.0
    networks:
      - smtp
    ports:
      - "1080:1080"
  web:
    container_name: application
    build: ./
    command: uwsgi --master --https :8000,RootCA.crt,RootCA.key --module app.wsgi --static-map /static=content/static
    ports:
      - "9000:8000"
    env_file:
      - .env.application
    volumes:
      - ./source/RootCA.crt:/app/source/RootCA.crt
      - ./source/RootCA.key:/app/source/RootCA.key
    depends_on:
      - smtp
      - db
    networks:
      - smtp
      - db

networks:
  db:
    driver: bridge
  smtp:
    driver: bridge

volumes:
  postgres_data: